/**!
    Fold
    (Un)folds content when a trigger/cmd is activated. Not an accordion, each fold is independent.
        Only for header (lang) of styleguide: fold-sc5.js is already taking care of help message, sc5-style
        STY-126 - Menu language is folded if an element not belonging to it is clicked elsewhere in the page

    @contributors: Philippe Vayssière (Alsacréations)
    @date-created: 2015-11-02
    @last-update: 2016-06-17
 */

;
(function($) {
  'use strict';
  var selFoldContainer = '.js-fold',
    selFoldCmd = '.js-fold-cmd',
    selFoldTarget = '.js-fold-target',
    selFoldAuto = '.js-fold-auto'; // see below for expected behaviour if present

  // Init: hides every foldable content
  $(document).ready(function() {
    var $target = $(selFoldTarget);
    if ($target.data('fold') === undefined) {
      $target.data('fold', '1');
      $target.addClass('js-hidden'); // Content initially hidden. This class should already be in HTML code generated by server, this is just in case©
    }

    // Hide/show content after click on command button
    // @BUGFIX $('body') and not $(selFoldContainer) because latter may not exist when event is created
    $('body').off('click.fold').on('click.fold', selFoldCmd, function() {
      $(this).toggleClass('is-active');
      $(this).closest(selFoldContainer).find(selFoldTarget).toggleClass('js-hidden');
    });
    // STY-126 Hide content (here: language menu) if a click occurs elsewhere in the page (and it was shown)
    // This behaviour happens when the container .js-fold also have .js-fold-auto class
    $('body').off('click.foldauto').on('click.foldauto', function(e) {
      var $parentFoldAuto = $(e.target).closest(selFoldAuto);
      // Is the clicked element elsewhere than in a .js-fold-auto component?
      if ($parentFoldAuto.length === 0) {
        var $foldContainer = $(selFoldContainer),
          $foldContainerCmd = $foldContainer.find(selFoldCmd),
          $foldContainerTarget = $foldContainer.find(selFoldTarget);
        if ($foldContainerCmd.hasClass('is-active')) {
          $foldContainerCmd.removeClass('is-active');
          $foldContainerTarget.addClass('js-hidden');
        }
      }
      // Closing _other_ foldauto if one is clicked
      if ($parentFoldAuto.length === 1) {
        var $otherFoldAuto = $(selFoldAuto).not($parentFoldAuto);
        $otherFoldAuto.each(function() {
          if ($(this).find(selFoldCmd).hasClass('is-active')) {
            $(this).find(selFoldCmd).removeClass('is-active');
            $(this).find(selFoldTarget).addClass('js-hidden');
          }
        });
      }
    });

  });

})(jQuery);