/**!
	1/ Hide a message if JS is activated
	2/ After a click on a button, display it (no hiding possible after that, it isn't (un)HelpMsging or toggling!)

	@contributors: Philippe Vayssière (Alsacréations)
	@date-created: 2016-06-10
	@last-update: 2016-06-10
 */

;(function($) {

	var selHelpMsgContainer = '.js-helpmsg',
		selHelpMsgCmd = '.js-helpmsg-cmd',
		selHelpMsgTarget = '.js-helpmsg-target';
	var breakpointSncf = '767px';

	// Init: hides relevant content
	$(function() {
		if (window.matchMedia("(max-width: "+breakpointSncf+")").matches) {
			// (mobile view only) Iframify calculates and set height of the iframe. We want the tallest height otherwise, when displaying help message, a scrollbar would appear.
			setTimeout(function () {
				$(selHelpMsgTarget).addClass('js-hidden'); // Content initially hidden. This class should already be in HTML code generated by server, this is just in case©
			}, 800);
		} else {
			$(selHelpMsgTarget).addClass('js-hidden');
		}

		// Ater click on command button: disable this command button and show content (can't be hidden anymore)
		$(selHelpMsgContainer).off('click.helpmsg').on('click.helpmsg', selHelpMsgCmd, function(e) {
			$(this).prop('disabled', 'disabled').addClass('is-disabled');
			$(this).closest(selHelpMsgContainer).find(selHelpMsgTarget).removeClass('js-hidden');
		});
	});


})(jQuery);